src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="date")
     */
    private $publish_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }
}

src/Controller/ListController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

class ListController extends AbstractController
{
    /**
     * @Route("/list", name="list")
     */

    public function index(Request $request, PostRepository $postRepository, PaginatorInterface $paginator): Response
    {
        $records = $postRepository->findAll();
        $records = $paginator->paginate(
            $records,
            $request->query->getInt('page', 1),
            5
        );
        return $this->render('list/index.html.twig', [
            'records' => $records
        ]);
    }

    /**
     * @Route("/list/detail/{id}", name="app_list_show", methods={"GET"})
     */
    public function show(Post $records): Response
    {
        return $this->render('list/detail.html.twig', [
            'records' => $records,
        ]);
    }
}

templates/list/detail.html.twig
{% extends 'base.html.twig' %} {% block
body %}
<nav
      class="navbar navbar-expand-lg navbar-light bg-light"
      style="height: 70px;"
    >
      <a class="navbar-brand" href="#">NeoTech Test By Mohammed Rafique</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent"></div>
      <ul class="nav navbar-nav navbar-right">
      
      <li><a class="nav-link" href="{{ path('app_logout') }}">Logout</a></li>
      
      </ul>

      
    </nav>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-light mb-3 mt-3">
        <div class="card-body">
          <AmpContent>
            <table class="table">
                <tr>
                    <th>Title</th>
                    <td>{{ records.title }}</td>
                </tr>
                <tr>
                    <th>Publish Date</th>
                    <td>{{ records.publishDate|date('m-d-Y') }}</td>
                </tr>
                <tr>
                    <th>Body</th>
                    <td>{{ records.body }}</td>
                </tr>
            </table>
          <NonAmpContent>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/list/index.html.twig
{# templates/list/index.html.twig #} {% extends 'base.html.twig' %} {% block
body %}
<nav
      class="navbar navbar-expand-lg navbar-light bg-light"
      style="height: 70px;"
    >
      <a class="navbar-brand" href="#">Login/Register App</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent"></div>
      <ul class="nav navbar-nav navbar-right">
      
      <li><a class="nav-link" href="{{ path('app_logout') }}">Logout</a></li>
      
      </ul>

      
    </nav>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-light mb-3 mt-3">
        <div class="card-body">
          <div class="card-header">List of posts available</div>
          <AmpContent>
          <table class="table">
            <tr>
              <th style="width: 3%;">Id</th>
              <th style="width: 7%;">Title</th>
              <th>Body</th>
              <th style="width: 10%;">Publish Date</th>
            </tr>
            {% for item in records %}
            
            <tr>
              <td>{{ item.id }}</td>
              <td>{{ item.title }}</td>
              <td>{{ item.body[:150] ~ '...' }} <a href="{{ path('app_list_show', {'id': item.id}) }}">Read More</a></td>
              <td>{{ item.publishDate|date('m-d-Y') }}</td>
            </tr>
            
            {% endfor %}
          </table>
          {{ knp_pagination_render(records) }}
          
</NonAmpContent>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}